package gui;

import hotel3h.Hotel;
import hotel3h.HotelDatabaseManager;
import hotel3h.Room;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 * @author Soley
 * 
 * Window which uses user input to create new room or edit an existing room
 */
public class EditOrAddRoomView extends javax.swing.JDialog {
    static Room r;
    static ArrayList<Hotel> hList;
    static int hotel;
    int addoredit; //1 if add, 0 if edit
    int nr,hnr,pets,count,washing,kitchen,minifridge,tv,bath,view,noise,smoke,ac,price,size,bed1,bed2,baby;
    /**
     * Creates new form EditOrAddRoomView
     * @param parent
     * @param modal
     * @param r1
     * @param h1
     * @param h
     */
    public EditOrAddRoomView(java.awt.Frame parent, boolean modal, Room r1, ArrayList<Hotel> h1, int h) {
        super(parent, modal);
        initComponents();
        r = r1;
        hList = h1;
        hotel = h;
        //if we are going to create a new room
        if(r==null){
            setForAdd();
        }
        //if we are editing an existing room
        else{
            getRoomValues();
            setRoomValues();
            jNumber.setEditable(false);
        }
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        babyGroup = new javax.swing.ButtonGroup();
        acGroup = new javax.swing.ButtonGroup();
        washingGroup = new javax.swing.ButtonGroup();
        tvGroup = new javax.swing.ButtonGroup();
        bathroomGroup = new javax.swing.ButtonGroup();
        smokingGroup = new javax.swing.ButtonGroup();
        minifridgeGroup = new javax.swing.ButtonGroup();
        kitchenGroup = new javax.swing.ButtonGroup();
        viewGroup = new javax.swing.ButtonGroup();
        noiseGroup = new javax.swing.ButtonGroup();
        petsGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jConfirm = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPetsYes = new javax.swing.JRadioButton();
        jPetsNo = new javax.swing.JRadioButton();
        jNoiseNo = new javax.swing.JRadioButton();
        jNoiseYes = new javax.swing.JRadioButton();
        jViewNo = new javax.swing.JRadioButton();
        jViewYes = new javax.swing.JRadioButton();
        jKitchenNo = new javax.swing.JRadioButton();
        jKitchenYes = new javax.swing.JRadioButton();
        jMinifridgeNo = new javax.swing.JRadioButton();
        jMinifridgeYes = new javax.swing.JRadioButton();
        jSmokingNo = new javax.swing.JRadioButton();
        jSmokingYes = new javax.swing.JRadioButton();
        jBathroomNo = new javax.swing.JRadioButton();
        jBathroomYes = new javax.swing.JRadioButton();
        jTVNo = new javax.swing.JRadioButton();
        jTVYes = new javax.swing.JRadioButton();
        jWashingNo = new javax.swing.JRadioButton();
        jWashingYes = new javax.swing.JRadioButton();
        jACNo = new javax.swing.JRadioButton();
        jACYes = new javax.swing.JRadioButton();
        jBabyNo = new javax.swing.JRadioButton();
        jBabyYes = new javax.swing.JRadioButton();
        jCountBox = new javax.swing.JComboBox<>();
        jBed1Box = new javax.swing.JComboBox<>();
        jBed2Box = new javax.swing.JComboBox<>();
        jPrice = new javax.swing.JTextField();
        jSize = new javax.swing.JTextField();
        jNumber = new javax.swing.JTextField();
        jHotelNr = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Please fill in the boxes");

        jLabel2.setText("Size (m2):");

        jLabel3.setText("Price (USD):");

        jLabel4.setText("Single beds:");

        jLabel5.setText("Double beds:");

        jLabel6.setText("Crib:");

        jLabel7.setText("Count:");

        jLabel8.setText("Air conditioner:");

        jLabel9.setText("Washing machine:");

        jLabel10.setText("TV:");

        jLabel11.setText("Bathroom:");

        jLabel12.setText("Smoking allowed:");

        jLabel13.setText("Minifridge:");

        jLabel14.setText("Kitchen:");

        jLabel15.setText("View");

        jLabel16.setText("Noice cancelling:");

        jLabel17.setText("Pets allowed:");

        jConfirm.setText("Confirm");
        jConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfirmActionPerformed(evt);
            }
        });

        jLabel18.setText("Number:");

        petsGroup.add(jPetsYes);
        jPetsYes.setText("Yes");
        jPetsYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPetsYesActionPerformed(evt);
            }
        });

        petsGroup.add(jPetsNo);
        jPetsNo.setText("No");
        jPetsNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPetsNoActionPerformed(evt);
            }
        });

        noiseGroup.add(jNoiseNo);
        jNoiseNo.setText("No");
        jNoiseNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNoiseNoActionPerformed(evt);
            }
        });

        noiseGroup.add(jNoiseYes);
        jNoiseYes.setText("Yes");
        jNoiseYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNoiseYesActionPerformed(evt);
            }
        });

        viewGroup.add(jViewNo);
        jViewNo.setText("No");
        jViewNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewNoActionPerformed(evt);
            }
        });

        viewGroup.add(jViewYes);
        jViewYes.setText("Yes");
        jViewYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jViewYesActionPerformed(evt);
            }
        });

        kitchenGroup.add(jKitchenNo);
        jKitchenNo.setText("No");
        jKitchenNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKitchenNoActionPerformed(evt);
            }
        });

        kitchenGroup.add(jKitchenYes);
        jKitchenYes.setText("Yes");
        jKitchenYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKitchenYesActionPerformed(evt);
            }
        });

        minifridgeGroup.add(jMinifridgeNo);
        jMinifridgeNo.setText("No");
        jMinifridgeNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMinifridgeNoActionPerformed(evt);
            }
        });

        minifridgeGroup.add(jMinifridgeYes);
        jMinifridgeYes.setText("Yes");
        jMinifridgeYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMinifridgeYesActionPerformed(evt);
            }
        });

        smokingGroup.add(jSmokingNo);
        jSmokingNo.setText("No");
        jSmokingNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSmokingNoActionPerformed(evt);
            }
        });

        smokingGroup.add(jSmokingYes);
        jSmokingYes.setText("Yes");
        jSmokingYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSmokingYesActionPerformed(evt);
            }
        });

        bathroomGroup.add(jBathroomNo);
        jBathroomNo.setText("No");
        jBathroomNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBathroomNoActionPerformed(evt);
            }
        });

        bathroomGroup.add(jBathroomYes);
        jBathroomYes.setText("Yes");
        jBathroomYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBathroomYesActionPerformed(evt);
            }
        });

        tvGroup.add(jTVNo);
        jTVNo.setText("No");
        jTVNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTVNoActionPerformed(evt);
            }
        });

        tvGroup.add(jTVYes);
        jTVYes.setText("Yes");
        jTVYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTVYesActionPerformed(evt);
            }
        });

        washingGroup.add(jWashingNo);
        jWashingNo.setText("No");
        jWashingNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWashingNoActionPerformed(evt);
            }
        });

        washingGroup.add(jWashingYes);
        jWashingYes.setText("Yes");
        jWashingYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWashingYesActionPerformed(evt);
            }
        });

        acGroup.add(jACNo);
        jACNo.setText("No");
        jACNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jACNoActionPerformed(evt);
            }
        });

        acGroup.add(jACYes);
        jACYes.setText("Yes");
        jACYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jACYesActionPerformed(evt);
            }
        });

        babyGroup.add(jBabyNo);
        jBabyNo.setText("No");
        jBabyNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBabyNoActionPerformed(evt);
            }
        });

        babyGroup.add(jBabyYes);
        jBabyYes.setText("Yes");
        jBabyYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBabyYesActionPerformed(evt);
            }
        });

        jCountBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jCountBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCountBoxActionPerformed(evt);
            }
        });

        jBed1Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        jBed1Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBed1BoxActionPerformed(evt);
            }
        });

        jBed2Box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        jBed2Box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBed2BoxActionPerformed(evt);
            }
        });

        jPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPriceActionPerformed(evt);
            }
        });

        jSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSizeActionPerformed(evt);
            }
        });

        jNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumberActionPerformed(evt);
            }
        });

        jHotelNr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jHotelNr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHotelNrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSize, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBed1Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCountBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jWashingYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jWashingNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTVYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTVNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBathroomYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBathroomNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSmokingYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSmokingNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMinifridgeYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jMinifridgeNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jKitchenYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jKitchenNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jViewYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jViewNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNoiseYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNoiseNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPetsYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPetsNo))
                    .addComponent(jConfirm)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBabyYes))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBabyNo)
                            .addComponent(jBed2Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPrice))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jACYes)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jACNo))
                    .addComponent(jHotelNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jHotelNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jBed1Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jBed2Box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jBabyYes)
                    .addComponent(jBabyNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCountBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jACYes)
                    .addComponent(jACNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jWashingYes)
                    .addComponent(jWashingNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTVYes)
                    .addComponent(jTVNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jBathroomYes)
                    .addComponent(jBathroomNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jSmokingYes)
                    .addComponent(jSmokingNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jMinifridgeYes)
                    .addComponent(jMinifridgeNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jKitchenYes)
                    .addComponent(jKitchenNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jViewYes)
                    .addComponent(jViewNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jNoiseYes)
                    .addComponent(jNoiseNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jPetsYes)
                    .addComponent(jPetsNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jConfirm)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //read price from user input
    private void jPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPriceActionPerformed
        // TODO add your handling code here:
        price = Integer.parseInt(jPrice.getText());
    }//GEN-LAST:event_jPriceActionPerformed

    //read size from user input
    private void jSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSizeActionPerformed
        // TODO add your handling code here:
        size = Integer.parseInt(jSize.getText());
    }//GEN-LAST:event_jSizeActionPerformed

    // gets chosen combobox item for number of single beds
    private void jBed1BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBed1BoxActionPerformed
        // TODO add your handling code here:
        bed1 = jBed1Box.getSelectedIndex();
    }//GEN-LAST:event_jBed1BoxActionPerformed

    //gets chosen combobox item for number of double beds
    private void jBed2BoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBed2BoxActionPerformed
        // TODO add your handling code here:
        bed2 = jBed2Box.getSelectedIndex();
    }//GEN-LAST:event_jBed2BoxActionPerformed

    //gets chosen combobox item for number of people
    private void jCountBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCountBoxActionPerformed
        // TODO add your handling code here:
        count = jCountBox.getSelectedIndex();
    }//GEN-LAST:event_jCountBoxActionPerformed

    //reads the user input for number
    private void jNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumberActionPerformed
        // TODO add your handling code here:
        nr = Integer.parseInt(jNumber.getText());
    }//GEN-LAST:event_jNumberActionPerformed

    /*
    * Next few functions set elements to 0 or 1 (no or yes) depending on which button was pressed
    */
    private void jBabyYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBabyYesActionPerformed
        // TODO add your handling code here:
        baby = 1;
    }//GEN-LAST:event_jBabyYesActionPerformed

    private void jBabyNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBabyNoActionPerformed
        // TODO add your handling code here:
        baby = 0;
    }//GEN-LAST:event_jBabyNoActionPerformed

    private void jACYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jACYesActionPerformed
        // TODO add your handling code here:
        ac = 1;
    }//GEN-LAST:event_jACYesActionPerformed

    private void jACNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jACNoActionPerformed
        // TODO add your handling code here:
        ac = 0;
    }//GEN-LAST:event_jACNoActionPerformed

    private void jWashingYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWashingYesActionPerformed
        // TODO add your handling code here:
        washing = 1;
    }//GEN-LAST:event_jWashingYesActionPerformed

    private void jWashingNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWashingNoActionPerformed
        // TODO add your handling code here:
        washing = 0;
    }//GEN-LAST:event_jWashingNoActionPerformed

    private void jTVYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTVYesActionPerformed
        // TODO add your handling code here:
        tv = 1;
    }//GEN-LAST:event_jTVYesActionPerformed

    private void jTVNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTVNoActionPerformed
        // TODO add your handling code here:
        tv = 0;
    }//GEN-LAST:event_jTVNoActionPerformed

    private void jBathroomYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBathroomYesActionPerformed
        // TODO add your handling code here:
        bath = 1;
    }//GEN-LAST:event_jBathroomYesActionPerformed

    private void jBathroomNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBathroomNoActionPerformed
        // TODO add your handling code here:
        bath = 0;
    }//GEN-LAST:event_jBathroomNoActionPerformed

    private void jSmokingYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSmokingYesActionPerformed
        // TODO add your handling code here:
        smoke = 1;
    }//GEN-LAST:event_jSmokingYesActionPerformed

    private void jSmokingNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSmokingNoActionPerformed
        // TODO add your handling code here:
        smoke = 0;
    }//GEN-LAST:event_jSmokingNoActionPerformed

    private void jMinifridgeYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMinifridgeYesActionPerformed
        // TODO add your handling code here:
        minifridge = 1;
    }//GEN-LAST:event_jMinifridgeYesActionPerformed

    private void jMinifridgeNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMinifridgeNoActionPerformed
        // TODO add your handling code here:
        minifridge = 0;
    }//GEN-LAST:event_jMinifridgeNoActionPerformed

    private void jKitchenYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKitchenYesActionPerformed
        // TODO add your handling code here:
        kitchen = 1;
    }//GEN-LAST:event_jKitchenYesActionPerformed

    private void jKitchenNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKitchenNoActionPerformed
        // TODO add your handling code here:
        kitchen = 0;
    }//GEN-LAST:event_jKitchenNoActionPerformed

    private void jViewYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewYesActionPerformed
        // TODO add your handling code here:
        view = 1;
    }//GEN-LAST:event_jViewYesActionPerformed

    private void jViewNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jViewNoActionPerformed
        // TODO add your handling code here:
        view = 0;
    }//GEN-LAST:event_jViewNoActionPerformed

    private void jNoiseYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNoiseYesActionPerformed
        // TODO add your handling code here:
        noise = 1;
    }//GEN-LAST:event_jNoiseYesActionPerformed

    private void jNoiseNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNoiseNoActionPerformed
        // TODO add your handling code here:
        noise = 0;
    }//GEN-LAST:event_jNoiseNoActionPerformed

    private void jPetsYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPetsYesActionPerformed
        // TODO add your handling code here:
        pets = 1;
    }//GEN-LAST:event_jPetsYesActionPerformed

    private void jPetsNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPetsNoActionPerformed
        // TODO add your handling code here:
        pets = 0;
    }//GEN-LAST:event_jPetsNoActionPerformed

    //adds a new room to the database or edits a room in the database and closes the window.
    private void jConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfirmActionPerformed
        // TODO add your handling code here:
        //edits a room
        //if(r != null){
            HotelDatabaseManager hdm = new HotelDatabaseManager();
        try {
            hdm.editRoom(nr, hnr, size, price, bed1, bed2, baby, pets, count, washing, kitchen, minifridge, tv, bath, view, noise, smoke, ac);
        } catch (SQLException ex) {
            Logger.getLogger(EditOrAddRoomView.class.getName()).log(Level.SEVERE, null, ex);
        }
        //}
        //Room rm = new Room(nr,hnr,pets,count,washing,kitchen,minifridge,tv,bath,view,noise,smoke,ac,price,size,bed1,bed2,baby);
        this.setVisible(false);
    }//GEN-LAST:event_jConfirmActionPerformed

    //gets the hotel number from user input
    private void jHotelNrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHotelNrActionPerformed
        // TODO add your handling code here:
        if(addoredit==1){
            hnr = jHotelNr.getSelectedIndex();
        }
    }//GEN-LAST:event_jHotelNrActionPerformed

    //reads all values from an existing room
        private void getRoomValues(){
        addoredit = 0;
        nr = r.getNr();
        hnr = r.getHnr();
        pets = r.getPets();
        count = r.getCount();
        washing = r.getWashing();
        kitchen = r.getKitchen();
        minifridge = r.getMinifridge();
        tv = r.getTv();
        bath = r.getBaby();
        view = r.getView();
        noise = r.getNoise();
        smoke = r.getSmoke();
        ac = r.getAc();
        price = r.getPrice();
        size = r.getSize();
        bed1 = r.getBed1();
        bed2 = r.getBed2();
        baby = r.getBaby();
    }
    
    //sets all values to the altered room
    private void setRoomValues(){
        if(pets==0){
            jPetsNo.setSelected(true);
        }
        else{
            jPetsYes.setSelected(true);
        }
        if(washing==0){
            jWashingNo.setSelected(true);
        }
        else{
            jWashingYes.setSelected(true);
        }
        if(kitchen==0){
            jKitchenNo.setSelected(true);
        }
        else{
            jKitchenYes.setSelected(true);
        }
        if(minifridge==0){
            jMinifridgeNo.setSelected(true);
        }
        else{
            jMinifridgeYes.setSelected(true);
        }
        if(tv==0){
            jTVNo.setSelected(true);
        }
        else{
            jTVYes.setSelected(true);
        }
        if(bath==0){
            jBathroomNo.setSelected(true);
        }
        else{
            jBathroomYes.setSelected(true);
        }
        if(view==0){
            jViewNo.setSelected(true);
        }
        else{
            jViewYes.setSelected(true);
        }
        if(noise==0){
            jNoiseNo.setSelected(true);
        }
        else{
            jNoiseYes.setSelected(true);
        }
        if(smoke==0){
            jSmokingNo.setSelected(true);
        }
        else{
            jSmokingYes.setSelected(true);
        }
        if(ac==0){
            jACNo.setSelected(true);
        }
        else{
            jACYes.setSelected(true);
        }
        if(baby==0){
            jBabyNo.setSelected(true);
        }
        else{
            jBabyYes.setSelected(true);
        }
        jHotelNr.setModel(new DefaultComboBoxModel(new String[]{"" + hnr}));
        jCountBox.setSelectedIndex(count);
        jBed1Box.setSelectedIndex(bed1);
        jBed2Box.setSelectedIndex(bed2);
        jSize.setText(""+size);
        jPrice.setText(""+price);
        jNumber.setText(""+nr);
        jHotelNr.setSelectedIndex(0);
        jHotelNr.setEnabled(false);
    }
    
    //sets all values to empty (or 0) for adding rooms
    private void setForAdd(){
        addoredit = 1;
        jPetsNo.setSelected(true);
        jWashingNo.setSelected(true);
        jKitchenNo.setSelected(true);
        jMinifridgeNo.setSelected(true);
        jTVNo.setSelected(true);
        jBathroomNo.setSelected(true);
        jViewNo.setSelected(true);
        jNoiseNo.setSelected(true);
        jSmokingNo.setSelected(true);
        jACNo.setSelected(true);
        jBabyNo.setSelected(true);
        String[] hNames = new String[hList.size()];
        Hotel[] hFylki = new Hotel[hList.size()];
        int temp = 0;
        for(Hotel h: hList){
            hNames[temp] = h.getName();
            hFylki[temp] = h;
            temp++;
        }
        if(hotel == 0){
            jHotelNr.setModel(new DefaultComboBoxModel(hNames));        
        }
        else{
            String[] s = {hNames[hotel-1]};
            jHotelNr.setModel(new DefaultComboBoxModel(s));
            jHotelNr.setEnabled(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditOrAddRoomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditOrAddRoomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditOrAddRoomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditOrAddRoomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditOrAddRoomView dialog = new EditOrAddRoomView(new javax.swing.JFrame(), true, r, hList, hotel);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup acGroup;
    private javax.swing.ButtonGroup babyGroup;
    private javax.swing.ButtonGroup bathroomGroup;
    private javax.swing.JRadioButton jACNo;
    private javax.swing.JRadioButton jACYes;
    private javax.swing.JRadioButton jBabyNo;
    private javax.swing.JRadioButton jBabyYes;
    private javax.swing.JRadioButton jBathroomNo;
    private javax.swing.JRadioButton jBathroomYes;
    private javax.swing.JComboBox<String> jBed1Box;
    private javax.swing.JComboBox<String> jBed2Box;
    private javax.swing.JButton jConfirm;
    private javax.swing.JComboBox<String> jCountBox;
    private javax.swing.JComboBox<String> jHotelNr;
    private javax.swing.JRadioButton jKitchenNo;
    private javax.swing.JRadioButton jKitchenYes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jMinifridgeNo;
    private javax.swing.JRadioButton jMinifridgeYes;
    private javax.swing.JRadioButton jNoiseNo;
    private javax.swing.JRadioButton jNoiseYes;
    private javax.swing.JTextField jNumber;
    private javax.swing.JRadioButton jPetsNo;
    private javax.swing.JRadioButton jPetsYes;
    private javax.swing.JTextField jPrice;
    private javax.swing.JTextField jSize;
    private javax.swing.JRadioButton jSmokingNo;
    private javax.swing.JRadioButton jSmokingYes;
    private javax.swing.JRadioButton jTVNo;
    private javax.swing.JRadioButton jTVYes;
    private javax.swing.JRadioButton jViewNo;
    private javax.swing.JRadioButton jViewYes;
    private javax.swing.JRadioButton jWashingNo;
    private javax.swing.JRadioButton jWashingYes;
    private javax.swing.ButtonGroup kitchenGroup;
    private javax.swing.ButtonGroup minifridgeGroup;
    private javax.swing.ButtonGroup noiseGroup;
    private javax.swing.ButtonGroup petsGroup;
    private javax.swing.ButtonGroup smokingGroup;
    private javax.swing.ButtonGroup tvGroup;
    private javax.swing.ButtonGroup viewGroup;
    private javax.swing.ButtonGroup washingGroup;
    // End of variables declaration//GEN-END:variables
}
