package gui;

import hotel3h.Hotel;
import hotel3h.HotelDatabaseManager;
import hotel3h.Room;
import java.util.ArrayList;

/**
 * @author Soley
 * 
 * A window which reads user inputs to alter a hotel or to create a new hotel
 * Communicates with HotelDatabaseManager to do that.
 */
public class EditOrAddHotelView extends javax.swing.JDialog {

    /**
     * Creates new form EditOrAddHotelView
     */
    static Hotel hotel;
    String name,address,website;
    int nr,type,gym,spa,pool,hottub,wifi,conference,restaurant,bar,inclusive,breakfast,cancellation,roomservice,wheelchair,elevator,flybus,stars,areacode;
    ArrayList<Room> rooms;
    int addoredit; //0 if adding a hotel, 1 if editing a hotel
    static int hotelnr;
    static int addRoom = 0;
    static int n;
    
    public EditOrAddHotelView(java.awt.Frame parent, boolean modal,Hotel h, int n1) {
        super(parent, modal);
        initComponents();
        hotel = h; //Null if it is no hotel, else the hotel to edit
        if(hotel == null){ //if no hotel we are clearly adding
            addoredit = 0;
        }
        else{ //editing a hotel
            setAllForHotel();
        }
        n = n1;
        setButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gymGroup = new javax.swing.ButtonGroup();
        spaGroup = new javax.swing.ButtonGroup();
        poolGroup = new javax.swing.ButtonGroup();
        hottubGroup = new javax.swing.ButtonGroup();
        wifiGroup = new javax.swing.ButtonGroup();
        conferenceGroup = new javax.swing.ButtonGroup();
        restaurantGroup = new javax.swing.ButtonGroup();
        barGroup = new javax.swing.ButtonGroup();
        allinGroup = new javax.swing.ButtonGroup();
        breakfastGroup = new javax.swing.ButtonGroup();
        cancellationGroup = new javax.swing.ButtonGroup();
        roomserviceGroup = new javax.swing.ButtonGroup();
        wheelchairGroup = new javax.swing.ButtonGroup();
        elevatorGroup = new javax.swing.ButtonGroup();
        flybusGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jAddRooms = new javax.swing.JButton();
        jConfirm = new javax.swing.JButton();
        jFlybusYes = new javax.swing.JRadioButton();
        jFlybusNo = new javax.swing.JRadioButton();
        jElevatorYes = new javax.swing.JRadioButton();
        jElevatorNo = new javax.swing.JRadioButton();
        jWheelchairYes = new javax.swing.JRadioButton();
        jWheelchairNo = new javax.swing.JRadioButton();
        jRoomServiceYes = new javax.swing.JRadioButton();
        jRoomServiceNo = new javax.swing.JRadioButton();
        jCancellationYes = new javax.swing.JRadioButton();
        jCancellationNo = new javax.swing.JRadioButton();
        jBreakfastYes = new javax.swing.JRadioButton();
        jBreakfastNo = new javax.swing.JRadioButton();
        jAllinYes = new javax.swing.JRadioButton();
        jAllinNo = new javax.swing.JRadioButton();
        jBarYes = new javax.swing.JRadioButton();
        jBarNo = new javax.swing.JRadioButton();
        jRestaurantYes = new javax.swing.JRadioButton();
        jRestaurantNo = new javax.swing.JRadioButton();
        jConferenceYes = new javax.swing.JRadioButton();
        jConferenceNo = new javax.swing.JRadioButton();
        jWifiYes = new javax.swing.JRadioButton();
        jWifiNo = new javax.swing.JRadioButton();
        jHottubYes = new javax.swing.JRadioButton();
        jHottubNo = new javax.swing.JRadioButton();
        jPoolYes = new javax.swing.JRadioButton();
        jPoolNo = new javax.swing.JRadioButton();
        jSpaYes = new javax.swing.JRadioButton();
        jSpaNo = new javax.swing.JRadioButton();
        jGymYes = new javax.swing.JRadioButton();
        jGymNo = new javax.swing.JRadioButton();
        jName = new javax.swing.JTextField();
        jAddress = new javax.swing.JTextField();
        jAreacode = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jWebsite = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Name:");

        jLabel2.setText("Address:");

        jLabel3.setText("Area code:");

        jLabel4.setText("Stars:");

        jLabel5.setText("Website:");

        jLabel6.setText("Type:");

        jLabel7.setText("Gym:");

        jLabel8.setText("Spa:");

        jLabel9.setText("Pool:");

        jLabel10.setText("Hot tub:");

        jLabel11.setText("Restaurant:");

        jLabel12.setText("Bar:");

        jLabel13.setText("All inclusive:");

        jLabel14.setText("Breakfast:");

        jLabel15.setText("Cancellation:");

        jLabel16.setText("Room service:");

        jLabel17.setText("Wheelchair accessible:");

        jLabel18.setText("Elevator access:");

        jLabel19.setText("Flybus:");

        jLabel20.setText("Rooms:");

        jLabel21.setText("Wifi");

        jLabel22.setText("Conference room:");

        jAddRooms.setText("Add Rooms");
        jAddRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddRoomsActionPerformed(evt);
            }
        });

        jConfirm.setText("Confirm");
        jConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfirmActionPerformed(evt);
            }
        });

        flybusGroup.add(jFlybusYes);
        jFlybusYes.setText("Yes");
        jFlybusYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFlybusYesActionPerformed(evt);
            }
        });

        flybusGroup.add(jFlybusNo);
        jFlybusNo.setText("No");
        jFlybusNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFlybusNoActionPerformed(evt);
            }
        });

        elevatorGroup.add(jElevatorYes);
        jElevatorYes.setText("Yes");
        jElevatorYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jElevatorYesActionPerformed(evt);
            }
        });

        elevatorGroup.add(jElevatorNo);
        jElevatorNo.setText("No");
        jElevatorNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jElevatorNoActionPerformed(evt);
            }
        });

        wheelchairGroup.add(jWheelchairYes);
        jWheelchairYes.setText("Yes");
        jWheelchairYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWheelchairYesActionPerformed(evt);
            }
        });

        wheelchairGroup.add(jWheelchairNo);
        jWheelchairNo.setText("No");
        jWheelchairNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWheelchairNoActionPerformed(evt);
            }
        });

        roomserviceGroup.add(jRoomServiceYes);
        jRoomServiceYes.setText("Yes");
        jRoomServiceYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRoomServiceYesActionPerformed(evt);
            }
        });

        roomserviceGroup.add(jRoomServiceNo);
        jRoomServiceNo.setText("No");
        jRoomServiceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRoomServiceNoActionPerformed(evt);
            }
        });

        cancellationGroup.add(jCancellationYes);
        jCancellationYes.setText("Yes");
        jCancellationYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancellationYesActionPerformed(evt);
            }
        });

        cancellationGroup.add(jCancellationNo);
        jCancellationNo.setText("No");
        jCancellationNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancellationNoActionPerformed(evt);
            }
        });

        breakfastGroup.add(jBreakfastYes);
        jBreakfastYes.setText("Yes");
        jBreakfastYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBreakfastYesActionPerformed(evt);
            }
        });

        breakfastGroup.add(jBreakfastNo);
        jBreakfastNo.setText("No");
        jBreakfastNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBreakfastNoActionPerformed(evt);
            }
        });

        allinGroup.add(jAllinYes);
        jAllinYes.setText("Yes");
        jAllinYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAllinYesActionPerformed(evt);
            }
        });

        allinGroup.add(jAllinNo);
        jAllinNo.setText("No");
        jAllinNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAllinNoActionPerformed(evt);
            }
        });

        barGroup.add(jBarYes);
        jBarYes.setText("Yes");
        jBarYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBarYesActionPerformed(evt);
            }
        });

        barGroup.add(jBarNo);
        jBarNo.setText("No");
        jBarNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBarNoActionPerformed(evt);
            }
        });

        restaurantGroup.add(jRestaurantYes);
        jRestaurantYes.setText("Yes");
        jRestaurantYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRestaurantYesActionPerformed(evt);
            }
        });

        restaurantGroup.add(jRestaurantNo);
        jRestaurantNo.setText("No");
        jRestaurantNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRestaurantNoActionPerformed(evt);
            }
        });

        conferenceGroup.add(jConferenceYes);
        jConferenceYes.setText("Yes");
        jConferenceYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConferenceYesActionPerformed(evt);
            }
        });

        conferenceGroup.add(jConferenceNo);
        jConferenceNo.setText("No");
        jConferenceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConferenceNoActionPerformed(evt);
            }
        });

        wifiGroup.add(jWifiYes);
        jWifiYes.setText("Yes");
        jWifiYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWifiYesActionPerformed(evt);
            }
        });

        wifiGroup.add(jWifiNo);
        jWifiNo.setText("No");
        jWifiNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWifiNoActionPerformed(evt);
            }
        });

        hottubGroup.add(jHottubYes);
        jHottubYes.setText("Yes");
        jHottubYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHottubYesActionPerformed(evt);
            }
        });

        hottubGroup.add(jHottubNo);
        jHottubNo.setText("No");
        jHottubNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHottubNoActionPerformed(evt);
            }
        });

        poolGroup.add(jPoolYes);
        jPoolYes.setText("Yes");
        jPoolYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPoolYesActionPerformed(evt);
            }
        });

        poolGroup.add(jPoolNo);
        jPoolNo.setText("No");
        jPoolNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPoolNoActionPerformed(evt);
            }
        });

        spaGroup.add(jSpaYes);
        jSpaYes.setText("Yes");
        jSpaYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSpaYesActionPerformed(evt);
            }
        });

        spaGroup.add(jSpaNo);
        jSpaNo.setText("No");
        jSpaNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSpaNoActionPerformed(evt);
            }
        });

        gymGroup.add(jGymYes);
        jGymYes.setText("Yes");
        jGymYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGymYesActionPerformed(evt);
            }
        });

        gymGroup.add(jGymNo);
        jGymNo.setText("No");
        jGymNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGymNoActionPerformed(evt);
            }
        });

        jAreacode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAreacodeActionPerformed(evt);
            }
        });
        jAreacode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jAreacodeKeyPressed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hotel", "Luxury Hotel", "Hostel", "Apartment/Flat", "Summer house", "Chest hotel", "Capsule hotel", "Motel", "Other" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel23.setText("Please fill in the boxes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAreacode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jWebsite))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jGymYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jGymNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSpaYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpaNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jPoolYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPoolNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jHottubYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jHottubNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBreakfastYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBreakfastNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCancellationYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCancellationNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRoomServiceYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRoomServiceNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jWheelchairYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jWheelchairNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jElevatorYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jElevatorNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFlybusYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFlybusNo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jAddRooms))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jWifiYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jWifiNo))
                    .addComponent(jConfirm)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAllinYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAllinNo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRestaurantYes))
                            .addComponent(jLabel22)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBarYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBarNo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRestaurantNo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jConferenceYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jConferenceNo))))
                    .addComponent(jLabel23)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jAreacode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jGymYes)
                    .addComponent(jGymNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jSpaYes)
                    .addComponent(jSpaNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jPoolYes)
                    .addComponent(jPoolNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jHottubYes)
                    .addComponent(jHottubNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jWifiYes)
                    .addComponent(jWifiNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jConferenceYes)
                            .addComponent(jConferenceNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jRestaurantYes)
                            .addComponent(jRestaurantNo))
                        .addGap(5, 5, 5)
                        .addComponent(jLabel12))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBarYes)
                        .addComponent(jBarNo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jAllinYes)
                    .addComponent(jAllinNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jBreakfastYes)
                    .addComponent(jBreakfastNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jCancellationYes)
                    .addComponent(jCancellationNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jRoomServiceYes)
                    .addComponent(jRoomServiceNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jWheelchairYes)
                    .addComponent(jWheelchairNo))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jElevatorYes)
                    .addComponent(jElevatorNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jFlybusYes)
                    .addComponent(jFlybusNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jAddRooms))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jConfirm)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //opens a new window to add rooms to the selected hotel
    private void jAddRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddRoomsActionPerformed
        // TODO add your handling code here:
        addRoom = 1;
        hotelnr = nr;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jAddRoomsActionPerformed
    
    //sets flybus to no/0
    private void jFlybusNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFlybusNoActionPerformed
        // TODO add your handling code here:
        flybus = 0;
    }//GEN-LAST:event_jFlybusNoActionPerformed
    
    //sets elevatoraccess to no/0
    private void jElevatorNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jElevatorNoActionPerformed
        // TODO add your handling code here:
        elevator = 0;
    }//GEN-LAST:event_jElevatorNoActionPerformed

    //sets wheelchair access to no / 0
    private void jWheelchairNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWheelchairNoActionPerformed
        // TODO add your handling code here:
        wheelchair = 0;
    }//GEN-LAST:event_jWheelchairNoActionPerformed

    //sets room service to no/0
    private void jRoomServiceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRoomServiceNoActionPerformed
        // TODO add your handling code here:
        roomservice = 0;
    }//GEN-LAST:event_jRoomServiceNoActionPerformed

    //sets free cancellation to no/0
    private void jCancellationNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancellationNoActionPerformed
        // TODO add your handling code here:
        cancellation = 0;
    }//GEN-LAST:event_jCancellationNoActionPerformed

    //sets breakfast to no/0
    private void jBreakfastNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBreakfastNoActionPerformed
        // TODO add your handling code here:
        breakfast = 0;
    }//GEN-LAST:event_jBreakfastNoActionPerformed
    //sets all inclusive to no / 0
    private void jAllinNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAllinNoActionPerformed
        // TODO add your handling code here:
        inclusive = 0;
    }//GEN-LAST:event_jAllinNoActionPerformed

    //sets bar to no / 0
    private void jBarNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBarNoActionPerformed
        // TODO add your handling code here:
        bar = 0;
    }//GEN-LAST:event_jBarNoActionPerformed

    //sets restaurant to no / 0
    private void jRestaurantNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRestaurantNoActionPerformed
        // TODO add your handling code here:
        restaurant = 0;
    }//GEN-LAST:event_jRestaurantNoActionPerformed

    //sets conference to no / 0
    private void jConferenceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConferenceNoActionPerformed
        // TODO add your handling code here:
        conference = 0;
    }//GEN-LAST:event_jConferenceNoActionPerformed

    //sets wifi to no/0
    private void jWifiNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWifiNoActionPerformed
        // TODO add your handling code here:
        wifi = 0;
    }//GEN-LAST:event_jWifiNoActionPerformed

    //sets hottub to no / 0
    private void jHottubNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHottubNoActionPerformed
        // TODO add your handling code here:
        hottub = 0;
    }//GEN-LAST:event_jHottubNoActionPerformed

    //sets pool to no/0
    private void jPoolNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPoolNoActionPerformed
        // TODO add your handling code here:
        pool = 0;
    }//GEN-LAST:event_jPoolNoActionPerformed

    //sets spa to no/0
    private void jSpaNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSpaNoActionPerformed
        // TODO add your handling code here:
        spa = 0;
    }//GEN-LAST:event_jSpaNoActionPerformed

    //sets gym to no/0
    private void jGymNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGymNoActionPerformed
        // TODO add your handling code here:
        gym = 0;
    }//GEN-LAST:event_jGymNoActionPerformed

    //reads input for area code
    private void jAreacodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAreacodeActionPerformed
        // TODO add your handling code here:
        areacode = Integer.parseInt(jAreacode.getText());
    }//GEN-LAST:event_jAreacodeActionPerformed

    //gets the selected type from the combobox
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        type = jComboBox2.getSelectedIndex();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    //gets the selected stars from the combobox
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        stars = jComboBox2.getSelectedIndex();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    //checks if input area code is accepted
    private void jAreacodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jAreacodeKeyPressed
        // TODO add your handling code here:
        if(jAreacode.getText().length()>2){
            jAreacode.setEditable(false);
            areacode = Integer.parseInt(jAreacode.getText());
            if(areacode>902||areacode<100){
                areacode = 0;
            }
        }
        if(evt.getKeyCode()==8){
            jAreacode.setEditable(true);
        }
    }//GEN-LAST:event_jAreacodeKeyPressed

    //adds the information to the database
    private void jConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfirmActionPerformed
        // TODO add your handling code here:
        //if we are editing a hotel
        if(hotel!= null){
            HotelDatabaseManager hdm = new HotelDatabaseManager();
            hdm.editHotel(name, address, website, stars, areacode, nr, type, gym, spa, pool, hottub, wifi, conference, restaurant, bar, inclusive, breakfast, cancellation, roomservice, wheelchair, elevator, flybus);
        }
        this.setVisible(false);
    }//GEN-LAST:event_jConfirmActionPerformed

    //sets gym to yes/1
    private void jGymYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGymYesActionPerformed
        // TODO add your handling code here:
        gym = 1;
    }//GEN-LAST:event_jGymYesActionPerformed

    //sets spa to yes/1
    private void jSpaYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSpaYesActionPerformed
        // TODO add your handling code here:
        spa = 1;
    }//GEN-LAST:event_jSpaYesActionPerformed

    //sets pool to yes/1
    private void jPoolYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPoolYesActionPerformed
        // TODO add your handling code here:
        pool = 1;
    }//GEN-LAST:event_jPoolYesActionPerformed

    //sets hottub to yes/1
    private void jHottubYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHottubYesActionPerformed
        // TODO add your handling code here:
        hottub = 1;
    }//GEN-LAST:event_jHottubYesActionPerformed

    //sets wifi to yes/1
    private void jWifiYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWifiYesActionPerformed
        // TODO add your handling code here:
        wifi = 1;
    }//GEN-LAST:event_jWifiYesActionPerformed

    //sets conference to yes/1
    private void jConferenceYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConferenceYesActionPerformed
        // TODO add your handling code here:
        conference = 1;
    }//GEN-LAST:event_jConferenceYesActionPerformed

    //sets restaurant to yes/1
    private void jRestaurantYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRestaurantYesActionPerformed
        // TODO add your handling code here:
        restaurant = 1;
    }//GEN-LAST:event_jRestaurantYesActionPerformed

    //sets bar to yes/1
    private void jBarYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBarYesActionPerformed
        // TODO add your handling code here:
        bar = 1;
    }//GEN-LAST:event_jBarYesActionPerformed

    //sets all inclusive to yes/1
    private void jAllinYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAllinYesActionPerformed
        // TODO add your handling code here:
        inclusive = 1;
    }//GEN-LAST:event_jAllinYesActionPerformed

    //sets breakfast to yes/1
    private void jBreakfastYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBreakfastYesActionPerformed
        // TODO add your handling code here:
        breakfast = 1;
    }//GEN-LAST:event_jBreakfastYesActionPerformed

    //sets cancellation to yes/1
    private void jCancellationYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancellationYesActionPerformed
        // TODO add your handling code here:
        cancellation = 1;
    }//GEN-LAST:event_jCancellationYesActionPerformed

    //sets roomservice to yes /1
    private void jRoomServiceYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRoomServiceYesActionPerformed
        // TODO add your handling code here:
        roomservice = 1;
    }//GEN-LAST:event_jRoomServiceYesActionPerformed

    //sets wheelchair access to yes/1
    private void jWheelchairYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWheelchairYesActionPerformed
        // TODO add your handling code here:
        wheelchair = 1;
    }//GEN-LAST:event_jWheelchairYesActionPerformed

    //sets elevator access to yes/1
    private void jElevatorYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jElevatorYesActionPerformed
        // TODO add your handling code here:
        elevator = 1;
    }//GEN-LAST:event_jElevatorYesActionPerformed

    //sets flybus to yes/1
    private void jFlybusYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFlybusYesActionPerformed
        // TODO add your handling code here:
        flybus = 1;
    }//GEN-LAST:event_jFlybusYesActionPerformed

    //set the buttons to the values of the selected hotel or all to no if the hotel is new
    private void setButtons(){
        if(addoredit==0 || hotel.getFlybus()<1){
            jFlybusNo.setSelected(true);
        }
        else{
            jFlybusYes.setSelected(true);
        }
        if(addoredit == 0 || hotel.getElevator()<1){
            jElevatorNo.setSelected(true);
        }
        else{
            jElevatorYes.setSelected(true);
        }        
        if(addoredit == 0 || hotel.getWheelchair()<1){
            jWheelchairNo.setSelected(true);
        }
        else{
            jWheelchairYes.setSelected(true);
        }
        if(addoredit == 0 || hotel.getRoomservice()<1){
            jRoomServiceNo.setSelected(true);
        }
        else{
            jRoomServiceYes.setSelected(true);
        }        
        if(addoredit==0 || hotel.getCancellation()<1){
            jCancellationNo.setSelected(true);
        }
        else{
            jCancellationYes.setSelected(true);
        }        
        if(addoredit==0 || hotel.getBreakfast()<1){
            jBreakfastNo.setSelected(true);
        }
        else{
            jBreakfastYes.setSelected(true);
        }        
        if(addoredit==0 || hotel.getInclusive()<1){
            jAllinNo.setSelected(true);
        }
        else{
            jAllinYes.setSelected(true);
        }        
        if(addoredit==0 || hotel.getBar()<1){
            jBarNo.setSelected(true);
        }
        else{
            jBarYes.setSelected(true);
        }
        if(addoredit == 0 || hotel.getRestaurant()<1){
            jRestaurantNo.setSelected(true);
        }
        else{
            jRestaurantYes.setSelected(true);
        }
        if(addoredit==0 || hotel.getConference()<1){
            jConferenceNo.setSelected(true);
        }
        else{
            jConferenceYes.setSelected(true);
        }        
        if(addoredit==0 || hotel.getWifi()<1){
            jWifiNo.setSelected(true);
        }
        else{
            jWifiYes.setSelected(true);
        }
        if(addoredit==0 || hotel.getHottub()<1){
            jHottubNo.setSelected(true);
        }
        else{
            jHottubYes.setSelected(true);
        }
        if(addoredit==0 || hotel.getPool()<1){
            jPoolNo.setSelected(true);
        }
        else{
            jPoolYes.setSelected(true);
        }
        if(addoredit==0 || hotel.getSpa()<1){
            jSpaNo.setSelected(true);
        }
        else{
            jSpaYes.setSelected(true);
        }
        if(addoredit==0 || hotel.getGym()<1){
            jGymNo.setSelected(true);
        }
        else{
            jGymYes.setSelected(true);
        }
    }
    
    //initialize all variables for an existing hotel
    private void setAllForHotel(){
        addoredit = 1;
        nr = hotel.getNr();
        type = hotel.getType();
        gym = hotel.getType();
        spa = hotel.getSpa();
        pool = hotel.getPool();
        hottub = hotel.getHottub();
        wifi = hotel.getWifi();
        conference = hotel.getConference();
        restaurant = hotel.getRestaurant();
        bar = hotel.getBar();
        inclusive = hotel.getInclusive();
        breakfast = hotel.getBreakfast();
        cancellation = hotel.getCancellation();
        roomservice = hotel.getRoomservice();
        wheelchair = hotel.getWheelchair();
        elevator = hotel.getElevator();
        flybus = hotel.getFlybus();
        stars = hotel.getStars();
        areacode = hotel.getAreacode();
        jAreacode.setText(""+areacode);
        name = hotel.getName();
        jName.setText(name);
        address = hotel.getAddress();
        jAddress.setText(address);
        website = hotel.getWebsite();
        jWebsite.setText(website);
        rooms = hotel.getRooms();
        jComboBox1.setSelectedIndex(stars);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditOrAddHotelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditOrAddHotelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditOrAddHotelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditOrAddHotelView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditOrAddHotelView dialog = new EditOrAddHotelView(new javax.swing.JFrame(), true, hotel,n);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup allinGroup;
    private javax.swing.ButtonGroup barGroup;
    private javax.swing.ButtonGroup breakfastGroup;
    private javax.swing.ButtonGroup cancellationGroup;
    private javax.swing.ButtonGroup conferenceGroup;
    private javax.swing.ButtonGroup elevatorGroup;
    private javax.swing.ButtonGroup flybusGroup;
    private javax.swing.ButtonGroup gymGroup;
    private javax.swing.ButtonGroup hottubGroup;
    private javax.swing.JButton jAddRooms;
    private javax.swing.JTextField jAddress;
    private javax.swing.JRadioButton jAllinNo;
    private javax.swing.JRadioButton jAllinYes;
    private javax.swing.JTextField jAreacode;
    private javax.swing.JRadioButton jBarNo;
    private javax.swing.JRadioButton jBarYes;
    private javax.swing.JRadioButton jBreakfastNo;
    private javax.swing.JRadioButton jBreakfastYes;
    private javax.swing.JRadioButton jCancellationNo;
    private javax.swing.JRadioButton jCancellationYes;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JRadioButton jConferenceNo;
    private javax.swing.JRadioButton jConferenceYes;
    private javax.swing.JButton jConfirm;
    private javax.swing.JRadioButton jElevatorNo;
    private javax.swing.JRadioButton jElevatorYes;
    private javax.swing.JRadioButton jFlybusNo;
    private javax.swing.JRadioButton jFlybusYes;
    private javax.swing.JRadioButton jGymNo;
    private javax.swing.JRadioButton jGymYes;
    private javax.swing.JRadioButton jHottubNo;
    private javax.swing.JRadioButton jHottubYes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jName;
    private javax.swing.JRadioButton jPoolNo;
    private javax.swing.JRadioButton jPoolYes;
    private javax.swing.JRadioButton jRestaurantNo;
    private javax.swing.JRadioButton jRestaurantYes;
    private javax.swing.JRadioButton jRoomServiceNo;
    private javax.swing.JRadioButton jRoomServiceYes;
    private javax.swing.JRadioButton jSpaNo;
    private javax.swing.JRadioButton jSpaYes;
    private javax.swing.JTextField jWebsite;
    private javax.swing.JRadioButton jWheelchairNo;
    private javax.swing.JRadioButton jWheelchairYes;
    private javax.swing.JRadioButton jWifiNo;
    private javax.swing.JRadioButton jWifiYes;
    private javax.swing.ButtonGroup poolGroup;
    private javax.swing.ButtonGroup restaurantGroup;
    private javax.swing.ButtonGroup roomserviceGroup;
    private javax.swing.ButtonGroup spaGroup;
    private javax.swing.ButtonGroup wheelchairGroup;
    private javax.swing.ButtonGroup wifiGroup;
    // End of variables declaration//GEN-END:variables
}
